FROM hashicorp/terraform:1.5.4

WORKDIR /mnt/curso-terraform

RUN apk update && apk add bash

ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV ARM_CLIENT_ID=${ARM_CLIENT_ID}
ENV ARM_TENANT_ID=${ARM_TENANT_ID}
ENV ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}
ENV ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET} 

ENTRYPOINT ["/bin/bash"]
